---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.core_dependencies
  - name: robertdebock.docker
  - name: robertdebock.epel
  - name: robertdebock.grub
  - name: robertdebock.hashicorp
  - name: robertdebock.python_pip
  - name: robertdebock.service
