---
# tasks file for nomad

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: create /etc/nomad.d
  file:
    path: /etc/nomad
    state: directory
    mode: "0750"
    owner: nomad
    group: nomad

- name: configure nomad server
  template:
    src: server.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad
  when:
    - nomad_server | bool

- name: configure nomad agent
  template:
    src: agent.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad
  when:
    - nomad_agent | bool

- name: start nomad
  service:
    name: nomad
    state: started
    enabled: yes

- name: determine nomad leader
  set_fact:
    nomad_leader: "{{ ansible_hostname }}"
  run_once: yes
  when:
    - nomad_server | bool

- name: list server members
  command: nomad server members
  register: nomad_list_server_members
  changed_when: no

- name: join nomad leader
  command: nomad server join {{ nomad_leader }}:4648
  register: nomad_join_nomad_leader
  when:
    - ansible_hostname != nomad_server
    - ansible_hostname not in nomad_list_server_members.stdout
