---

- name: configure nomad server
  template:
    src: server.hcl.j2
    dest: /etc/nomad/server.hcl
  notify:
    - restart nomad server

- name: create nomad server service
  include_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: nomad-server
        description: The nomad server
        start_command: nomad agent -config /etc/nomad/server.hcl

- name: start nomad server
  service:
    name: nomad-server
    state: started
    enabled: yes
