---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check server members
      ansible.builtin.command:
        cmd: nomad server members
      changed_when: false

    - name: Check node status
      ansible.builtin.command:
        cmd: nomad node status
      changed_when: false

    - name: Initialize example job
      ansible.builtin.command:
        cmd: nomad init example.nomad
      args:
        creates: example.nomad

    - name: Run and stop example job
      when:
        - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
      block:
        - name: Run example job
          ansible.builtin.command:
            cmd: nomad job run example.nomad
          changed_when: false

        - name: Stop example job
          ansible.builtin.command:
            cmd: nomad job stop example
          changed_when: false

    - name: Check the ui
      ansible.builtin.uri:
        url: "http://localhost:4646/ui/"
