---
name: molecule

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "27 14 14 * *"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "8"
          - image: "fedora"
            tag: "36"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@5.0.2
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
